# One message model with a diagonalizable square matrix

James Yu, 10 July 2022

In [1]:
import numpy as np
from sympy import *

Let $K = P^\prime P$ be a symmetric matrix. Then:

In [2]:
k11, k12, k13, k22, k23, k33 = symbols("K_11 K_12 K_13 K_22 K_23 K_33")
K = Matrix([[k11, k12, k13], [k12, k22, k23], [k13, k23, k33]])
K

Matrix([
[K_11, K_12, K_13],
[K_12, K_22, K_23],
[K_13, K_23, K_33]])

In [3]:
l1, l2, l3 = symbols("lambda_1 lambda_2 lambda_3")
D = Matrix([[l1, 0, 0], [0, l2, 0], [0, 0, l3]])
D

Matrix([
[lambda_1,        0,        0],
[       0, lambda_2,        0],
[       0,        0, lambda_3]])

In [4]:
D * K * D

Matrix([
[      K_11*lambda_1**2, K_12*lambda_1*lambda_2, K_13*lambda_1*lambda_3],
[K_12*lambda_1*lambda_2,       K_22*lambda_2**2, K_23*lambda_2*lambda_3],
[K_13*lambda_1*lambda_3, K_23*lambda_2*lambda_3,       K_33*lambda_3**2]])

In [5]:
D * D * K * D * D

Matrix([
[            K_11*lambda_1**4, K_12*lambda_1**2*lambda_2**2, K_13*lambda_1**2*lambda_3**2],
[K_12*lambda_1**2*lambda_2**2,             K_22*lambda_2**4, K_23*lambda_2**2*lambda_3**2],
[K_13*lambda_1**2*lambda_3**2, K_23*lambda_2**2*lambda_3**2,             K_33*lambda_3**4]])

In [6]:
D * D * D * K * D * D * D

Matrix([
[            K_11*lambda_1**6, K_12*lambda_1**3*lambda_2**3, K_13*lambda_1**3*lambda_3**3],
[K_12*lambda_1**3*lambda_2**3,             K_22*lambda_2**6, K_23*lambda_2**3*lambda_3**3],
[K_13*lambda_1**3*lambda_3**3, K_23*lambda_2**3*lambda_3**3,             K_33*lambda_3**6]])

In [7]:
simplify(K + (D * K * D) + (D * D * K * D * D) + (D * D * D * K * D * D * D))

Matrix([
[                              K_11*(lambda_1**6 + lambda_1**4 + lambda_1**2 + 1), K_12*(lambda_1**3*lambda_2**3 + lambda_1**2*lambda_2**2 + lambda_1*lambda_2 + 1), K_13*(lambda_1**3*lambda_3**3 + lambda_1**2*lambda_3**2 + lambda_1*lambda_3 + 1)],
[K_12*(lambda_1**3*lambda_2**3 + lambda_1**2*lambda_2**2 + lambda_1*lambda_2 + 1),                               K_22*(lambda_2**6 + lambda_2**4 + lambda_2**2 + 1), K_23*(lambda_2**3*lambda_3**3 + lambda_2**2*lambda_3**2 + lambda_2*lambda_3 + 1)],
[K_13*(lambda_1**3*lambda_3**3 + lambda_1**2*lambda_3**2 + lambda_1*lambda_3 + 1), K_23*(lambda_2**3*lambda_3**3 + lambda_2**2*lambda_3**2 + lambda_2*lambda_3 + 1),                               K_33*(lambda_3**6 + lambda_3**4 + lambda_3**2 + 1)]])

Let the above matrix be denoted as $G^3$. Then we can easily see that $G_{i,j}^3 = K_{ij}((\lambda_i \lambda_j)^3 + (\lambda_i \lambda_j)^2 + (\lambda_i \lambda_j) + 1)$. This, extended to infinity, is a scalar infinite geometric series and so it has a solution: 

$$G^*_{i, j} = \frac{K_{ij}}{1 - \lambda_i \lambda_j}$$

This generalizes to arbitrary dimensions based on the behaviour of $DKD$ in general.

In [8]:
A = np.array([
    [0.3, 0.5, 0.2],
    [0.3, 0.5, 0.2],
    [0.3, 0.5, 0.2]
])

In [9]:
eigvals, P = np.linalg.eig(A)
D = np.diag(eigvals)
print(D)
print(P)

[[ 1.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  3.6626128e-17  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00 -2.1707311e-17]]
[[ 0.57735027 -0.84998461  0.3933008 ]
 [ 0.57735027  0.35389685 -0.53505413]
 [ 0.57735027  0.39023479  0.74768413]]


In [10]:
P @ D @ np.linalg.inv(P)

array([[0.3, 0.5, 0.2],
       [0.3, 0.5, 0.2],
       [0.3, 0.5, 0.2]])

Now, we wish to compute the sum (let $\delta = 1$ and start at $t = 0$ instead of $t = 1$ to get the idea across for now, it can be changed  later):
$$\sum\limits_{t = 0}^\infty \mathbf{y}_0^\prime (A^t)^\prime A^t \mathbf{y}_0$$

where $A = PDP^{-1}$ is diagonalizable.

It follows that we can compute the equivalent $\mathbf{y}_0^\prime [\sum\limits_{t = 0}^\infty (A^t)^\prime A^t]\mathbf{y}_0$.

The sum on the inside then evaluates to $\sum\limits_{t = 0}^\infty ((PDP^{-1})^t)^\prime (PDP^{-1})^t$.

$$= \sum\limits_{t = 0}^\infty (PD^t P^{-1})^\prime PD^tP^{-1}$$

$$= \sum\limits_{t = 0}^\infty (P^{-1})^\prime D^t P^\prime PD^tP^{-1}$$

$$= (P^{-1})^\prime [\sum\limits_{t = 0}^\infty  D^t P^\prime PD^t]P^{-1}$$

And now, using the solution we obtained above, each entry of the inner sum in brackets above is now: 
$$\frac{(P^\prime P)_{ij}}{1 - \lambda_i \lambda_j}$$

Notice that if $P^\prime = P^{-1}$, then $P^\prime P = I$ where $I_{ii} = 1$ and $I_{ij} = 0$ for $i \neq j$ and we get that the inner sum is a diagonal matrix where each entry with index $i$ is of the form:

$$\frac{1}{1 - \lambda_i^2}$$

As it is diagonal, this is the same solution as $(I - D^2)^{-1}$, since the inverse of a diagonal matrix is the matrix of reciprocal diagonals. This means that the general solution is indeed a generalization of the one we already have for symmetric matrices.

In [11]:
eigvals

array([ 1.0000000e+00,  3.6626128e-17, -2.1707311e-17])

In [12]:
sum([0.9**t * np.linalg.matrix_power(A, t).T @ np.linalg.matrix_power(A, t) for t in range(10000)]) # brute force direct

array([[3.43, 4.05, 1.62],
       [4.05, 7.75, 2.7 ],
       [1.62, 2.7 , 2.08]])

In [13]:
G_brute_force = sum([0.9 ** t * np.linalg.matrix_power(D, t) @ P.T @ P @ np.linalg.matrix_power(D, t) for t in range(10000)])
G_brute_force # brute force inner sum with diagonalization

array([[10.        , -0.06111424,  0.34983431],
       [-0.06111424,  1.        , -0.23188123],
       [ 0.34983431, -0.23188123,  1.        ]])

In [14]:
np.linalg.inv(P).T @ G_brute_force @ np.linalg.inv(P) # brute force total expression with diagonalization

array([[3.43, 4.05, 1.62],
       [4.05, 7.75, 2.7 ],
       [1.62, 2.7 , 2.08]])

In [15]:
G = (P.T @ P) * np.array([ # elementwise multiply
    [1/(1 - 0.9 * eigvals[0] * eigvals[0]), 1/(1 - 0.9 * eigvals[0] * eigvals[1]), 1/(1 - 0.9 * eigvals[0] * eigvals[2])],
    [1/(1 - 0.9 * eigvals[1] * eigvals[0]), 1/(1 - 0.9 * eigvals[1] * eigvals[1]), 1/(1 - 0.9 * eigvals[1] * eigvals[2])],
    [1/(1 - 0.9 * eigvals[2] * eigvals[0]), 1/(1 - 0.9 * eigvals[2] * eigvals[1]), 1/(1 - 0.9 * eigvals[2] * eigvals[2])],
])
G

array([[10.        , -0.06111424,  0.34983431],
       [-0.06111424,  1.        , -0.23188123],
       [ 0.34983431, -0.23188123,  1.        ]])

In [16]:
np.linalg.inv(P).T @ G @ np.linalg.inv(P) # total expression using analytical solution

array([[3.43, 4.05, 1.62],
       [4.05, 7.75, 2.7 ],
       [1.62, 2.7 , 2.08]])