# Different Agendas ($K^*$ and projection data only)
Unified Model with Multiple Strategic Agents\
James Yu, 31 October 2022

In [1]:
from collections import namedtuple #,defaultdict
import matplotlib.pyplot as plt
import numpy as np
from numpy.linalg import inv as npinv
from numpy.linalg import matrix_power as nppow

In [2]:
def infinite_solution(A, delta, c, M = 1):
    n = 3
    eps = np.finfo(np.float64).eps
    I = np.identity(n)
    eigvals, U = np.linalg.eig(A)
    D = np.diag(eigvals)
    K_t = I
    K_sequence = [K_t]
    
    while True: #for i in range(T): # generate solution matrices
        K_t_new = I + c * delta * (delta * K_t + c * I) @ nppow(npinv(M * delta * K_t + c * I), 2) @ K_t @ nppow(D, 2)
        K_sequence.insert(0, K_t_new)
        if np.allclose(K_t, K_t_new, rtol = eps, atol = eps): break
        K_t = K_t_new

    K_ss = K_sequence[0]
    return K_ss, D, U

In [3]:
# taken from higher_cost_version.ipynb
A = np.array([ # balanced
    [0.48, 0.3, 0.22],
    [0.3, 0.52, 0.18],
    [0.22, 0.18, 0.6]
])

A_alt = np.array([ # stubborn
    [0.9, 0.07, 0.03],
    [0.07, 0.58, 0.35],
    [0.03, 0.35, 0.62]
])

A_identical = np.array([ # identical
    [0.6, 0.2, 0.2],
    [0.2, 0.6, 0.2],
    [0.2, 0.2, 0.6]
])

In [4]:
delta = 0.9
c = 0.5
K_ss, D, U = infinite_solution(A, delta, c, M = 2) # balanced

In [5]:
K_ss

array([[1.12006384, 0.        , 0.        ],
       [0.        , 1.00449158, 0.        ],
       [0.        , 0.        , 1.01964356]])

In [6]:
D

array([[1.        , 0.        , 0.        ],
       [0.        , 0.19416995, 0.        ],
       [0.        , 0.        , 0.40583005]])

In [7]:
U

array([[-0.57735027, -0.76505532, -0.28523152],
       [-0.57735027,  0.6295454 , -0.51994159],
       [-0.57735027,  0.13550992,  0.8051731 ]])

In [8]:
K_ss_, D_, U_ = infinite_solution(A_alt, delta, c, M = 2) # stubborn

In [9]:
K_ss_

array([[1.12006384, 0.        , 0.        ],
       [0.        , 1.08697763, 0.        ],
       [0.        , 0.        , 1.0073292 ]])

In [10]:
D_

array([[1.        , 0.        , 0.        ],
       [0.        , 0.85199338, 0.        ],
       [0.        , 0.        , 0.24800662]])

In [11]:
U_

array([[ 0.57735027,  0.8151481 ,  0.04690676],
       [ 0.57735027, -0.3669516 , -0.72939234],
       [ 0.57735027, -0.44819649,  0.68248558]])

In [12]:
K_ss__, D__, U__ = infinite_solution(A_identical, delta, c, M = 2) # identical

In [13]:
K_ss__

array([[1.01908243, 0.        , 0.        ],
       [0.        , 1.12006384, 0.        ],
       [0.        , 0.        , 1.01908243]])

In [14]:
D__

array([[0.4, 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0. , 0.4]])

In [15]:
U__

array([[-0.81649658,  0.57735027, -0.26683061],
       [ 0.40824829,  0.57735027, -0.53486687],
       [ 0.40824829,  0.57735027,  0.80169748]])