# Experiments with the Schur complement test

James Yu, 21 December 2021

In [1]:
import numpy as np
from sympy import *

$$M = LHS - RHS = \begin{bmatrix}Q & \tilde A^\prime\\\tilde A & -\tilde B R^{-1}\tilde B^\prime\end{bmatrix} - \begin{bmatrix}Q & A^\prime\\A & - B R^{-1} B^\prime\end{bmatrix}$$

$$=  \begin{bmatrix}0 & (\tilde A - A)^\prime\\\tilde A - A & (-\tilde B R^{-1}\tilde B^\prime) - (-B R^{-1} B^\prime)\end{bmatrix}$$

The task is to ensure that this matrix is positive semidefinite. First, ensuring the bottom right block matrix is positive definite.

In [2]:
B = np.array([
    [0.5], 
    [0.5]], ndmin = 2)
tilde_B = np.array([
    [0.2], 
    [0.3]], ndmin = 2)
mat = (-(tilde_B @ tilde_B.T)) - (-(B @ B.T))
print(mat)
np.linalg.eigvals(mat) # note R = I_1 so R^{-1} = I_1

[[0.21 0.19]
 [0.19 0.16]]


array([ 0.37663768, -0.00663768])

This is positive semidefinite, which would not work.

In [6]:
B = np.array([
    [0.5, 0.3], 
    [0, 0.5]], ndmin = 2)
tilde_B = np.array([
    [0.2, 0], 
    [0, 0.2]], ndmin = 2)
mat = (-(tilde_B @ tilde_B.T)) - (-(B @ B.T))
print(mat)
np.linalg.eigvals(mat)

[[0.3  0.15]
 [0.15 0.21]]


array([0.4116046, 0.0983954])

This, however, is positive definite, and would generalize to arbitrary diagonals creating $(-\tilde B R^{-1}\tilde B^\prime) - (-B R^{-1} B^\prime) = c I_n$ for some constant $c > 0$. Then:

$$M = \begin{bmatrix}0 & (\tilde A - A)^\prime\\\tilde A - A & c I_n\end{bmatrix}$$

Next, $\frac{1}{c}(\tilde A - A)^\prime(\tilde A - A)$ must be negative semidefinite. $c > 0$, so:

$\succ$

In [8]:
B = np.array([
    [0.5, 0.3], 
    [0, 0.5]], ndmin = 2)
tilde_B = np.array([
    [0.2, 0], 
    [0, 0.2]], ndmin = 2)

A = np.array([
    [0.2, 0], 
    [0, 0.5]], ndmin = 2)
tilde_A = np.array([
    [0.5, 0.3], 
    [0.4, 0.4]], ndmin = 2)

mat = tilde_A - A
print(mat)
print()
print(-mat.T @ ((-(tilde_B @ tilde_B.T)) - (-(B @ B.T))) @ mat)
np.linalg.eigvals(-mat.T @ ((-(tilde_B @ tilde_B.T)) - (-(B @ B.T))) @ mat) # <- this must be positive definite: A - BC^{-1}B'

[[ 0.3  0.3]
 [ 0.4 -0.1]]

[[-0.0966 -0.0321]
 [-0.0321 -0.0201]]


array([-0.10828468, -0.00841532])

An issue: $X^\prime X$ is positive semidefinite for any $X$.

(Proof: $y^\prime X^\prime X y$ where $y$ is $n$ by 1 and $X$ is $m$ by $n$ yields $Xy$ as an $m$ by 1 vector multiplied by $y^\prime X^\prime = (Xy)^\prime$. This is of the form:

$$(Xy)_1^2 + (Xy)_2^2 + \dots \geq 0$$
So this must be positive semidefinite.