# Unified Model with Integrated Bot: Higher $c$, same $\delta$

James Yu, 17 August 2022

In [1]:
import matplotlib.pyplot as plt
import numpy as np
from numpy.linalg import inv
np.set_printoptions(suppress=True) # disable scientific notation for readability

In [2]:
def infinite_solution(A_n, A_c, delta, c):
    n = 3
    eps = np.finfo(np.float64).eps
    I = np.identity(n)
    O = np.zeros((n, n))
    
    Q = np.block([
        [I, O], 
        [O, O]
    ])
    A = np.block([
        [A_n, A_c], 
        [O, I]
    ])
    B = np.block([
        [I],
        [O]
    ])
    K_t = Q
    K_sequence = [K_t]
    
    while True: # generate solution matrices; note I divide delta into the inverse term for simplification
        K_t_new = Q + delta * A.T @ (K_t - K_t @ B @ inv(B.T @ K_t @ B + c * I / delta) @ B.T @ K_t) @ A
        K_sequence.insert(0, K_t_new)
        if np.allclose(K_t, K_t_new, rtol = eps, atol = eps): break
        K_t = K_t_new

    K_ss = K_sequence[0]
    L_ss = -inv(B.T @ K_ss @ B + c * I / delta) @ B.T @ K_ss @ A
    return K_ss, L_ss

# 1. Highly symmetric

In [3]:
A_1_n = 0.99 * np.array([
    [0.5, 0.25, 0.25],
    [0.25, 0.5, 0.25],
    [0.25, 0.25, 0.5]
])
A_1_c = np.diag([0.01, 0.01, 0.01])
delta = 0.999 
c = 5.0 # different c, same delta

In [4]:
K_ss, L_ss = infinite_solution(A_1_n, A_1_c, delta, c)

In [5]:
print(K_ss)

[[1.6119321  0.55868406 0.55868406 0.01797651 0.0152728  0.0152728 ]
 [0.55868406 1.6119321  0.55868406 0.0152728  0.01797651 0.0152728 ]
 [0.55868406 0.55868406 1.6119321  0.0152728  0.0152728  0.01797651]
 [0.01797651 0.0152728  0.0152728  0.2534661  0.12311618 0.12311618]
 [0.0152728  0.01797651 0.0152728  0.12311618 0.2534661  0.12311618]
 [0.0152728  0.0152728  0.01797651 0.12311618 0.12311618 0.2534661 ]]


In [6]:
sum(K_ss)

array([2.77782233, 2.77782233, 2.77782233, 0.54822056, 0.54822056,
       0.54822056])

In [7]:
print(L_ss)

[[-0.14513701 -0.10210829 -0.10210829 -0.00472403 -0.00253921 -0.00253921]
 [-0.10210829 -0.14513701 -0.10210829 -0.00253921 -0.00472403 -0.00253921]
 [-0.10210829 -0.10210829 -0.14513701 -0.00253921 -0.00253921 -0.00472403]]


In [8]:
sum(L_ss)

array([-0.34935358, -0.34935358, -0.34935358, -0.00980245, -0.00980245,
       -0.00980245])

In [9]:
sum(L_ss.T)

array([-0.35915603, -0.35915603, -0.35915603])

# 2. Completely uniform

In [10]:
A_2_n = np.array([
    [0.25, 0.25, 0.25],
    [0.25, 0.25, 0.25],
    [0.25, 0.25, 0.25]
])
A_2_c = np.diag([0.25, 0.25, 0.25])

In [11]:
K_ss, L_ss = infinite_solution(A_2_n, A_2_c, delta, c)

In [12]:
print(K_ss)

[[  1.23967587   0.23967587   0.23967587   0.18062886   0.18062886
    0.18062886]
 [  0.23967587   1.23967587   0.23967587   0.18062886   0.18062886
    0.18062886]
 [  0.23967587   0.23967587   1.23967587   0.18062886   0.18062886
    0.18062886]
 [  0.18062886   0.18062886   0.18062886 113.93963424  61.89971092
   61.89971092]
 [  0.18062886   0.18062886   0.18062886  61.89971092 113.93963424
   61.89971092]
 [  0.18062886   0.18062886   0.18062886  61.89971092  61.89971092
  113.93963424]]


In [13]:
sum(K_ss)

array([  2.26091421,   2.26091421,   2.26091421, 238.28094268,
       238.28094268, 238.28094268])

In [14]:
print(L_ss)

[[-0.06391357 -0.06391357 -0.06391357 -0.07592232 -0.03429038 -0.03429038]
 [-0.06391357 -0.06391357 -0.06391357 -0.03429038 -0.07592232 -0.03429038]
 [-0.06391357 -0.06391357 -0.06391357 -0.03429038 -0.03429038 -0.07592232]]


In [15]:
sum(L_ss)

array([-0.1917407 , -0.1917407 , -0.1917407 , -0.14450309, -0.14450309,
       -0.14450309])

In [16]:
sum(L_ss.T)

array([-0.33624379, -0.33624379, -0.33624379])

# 3. No inter-agent links

In [17]:
A_3_n = 0.5 * np.identity(3)
A_3_c = np.diag([0.5, 0.5, 0.5])

In [18]:
K_ss, L_ss = infinite_solution(A_3_n, A_3_c, delta, c)

In [19]:
print(np.round(K_ss, 5))

[[  1.24976   0.        0.        0.41606   0.        0.     ]
 [  0.        1.24976   0.        0.        0.41606   0.     ]
 [  0.        0.        1.24976   0.        0.        0.41606]
 [  0.41606   0.        0.      554.70699   0.        0.     ]
 [  0.        0.41606   0.        0.      554.70699   0.     ]
 [  0.        0.        0.41606   0.        0.      554.70699]]


In [20]:
sum(K_ss)

array([  1.6658203,   1.6658203,   1.6658203, 555.1230496, 555.1230496,
       555.1230496])

In [21]:
print(L_ss)

[[-0.09990475  0.          0.         -0.16642337  0.          0.        ]
 [ 0.         -0.09990475  0.          0.         -0.16642337  0.        ]
 [ 0.          0.         -0.09990475  0.          0.         -0.16642337]]


In [22]:
sum(L_ss)

array([-0.09990475, -0.09990475, -0.09990475, -0.16642337, -0.16642337,
       -0.16642337])

In [23]:
sum(L_ss.T)

array([-0.26632812, -0.26632812, -0.26632812])