# Unified Model with Integrated Bot: Lower $c$, same $\delta$

James Yu, 17 August 2022

In [1]:
import matplotlib.pyplot as plt
import numpy as np
from numpy.linalg import inv
np.set_printoptions(suppress=True) # disable scientific notation for readability

In [2]:
def infinite_solution(A_n, A_c, delta, c):
    n = 3
    eps = np.finfo(np.float64).eps
    I = np.identity(n)
    O = np.zeros((n, n))
    
    Q = np.block([
        [I, O], 
        [O, O]
    ])
    A = np.block([
        [A_n, A_c], 
        [O, I]
    ])
    B = np.block([
        [I],
        [O]
    ])
    K_t = Q
    K_sequence = [K_t]
    
    while True: # generate solution matrices; note I divide delta into the inverse term for simplification
        K_t_new = Q + delta * A.T @ (K_t - K_t @ B @ inv(B.T @ K_t @ B + c * I / delta) @ B.T @ K_t) @ A
        K_sequence.insert(0, K_t_new)
        if np.allclose(K_t, K_t_new, rtol = eps, atol = eps): break
        K_t = K_t_new

    K_ss = K_sequence[0]
    L_ss = -inv(B.T @ K_ss @ B + c * I / delta) @ B.T @ K_ss @ A
    return K_ss, L_ss

# 1. Highly symmetric

In [3]:
A_1_n = 0.99 * np.array([
    [0.5, 0.25, 0.25],
    [0.25, 0.5, 0.25],
    [0.25, 0.25, 0.5]
])
A_1_c = np.diag([0.01, 0.01, 0.01])
delta = 0.999 
c = 0.1 # different c, same delta

In [4]:
K_ss, L_ss = infinite_solution(A_1_n, A_1_c, delta, c)

In [5]:
print(K_ss)

[[1.0336356  0.02806454 0.02806454 0.00048317 0.00025292 0.00025292]
 [0.02806454 1.0336356  0.02806454 0.00025292 0.00048317 0.00025292]
 [0.02806454 0.02806454 1.0336356  0.00025292 0.00025292 0.00048317]
 [0.00048317 0.00025292 0.00025292 0.00964213 0.00017888 0.00017888]
 [0.00025292 0.00048317 0.00025292 0.00017888 0.00964213 0.00017888]
 [0.00025292 0.00025292 0.00048317 0.00017888 0.00017888 0.00964213]]


In [6]:
sum(K_ss)

array([1.09075369, 1.09075369, 1.09075369, 0.01098888, 0.01098888,
       0.01098888])

In [7]:
print(L_ss)

[[-0.45229999 -0.22720699 -0.22720699 -0.00953191 -0.000229   -0.000229  ]
 [-0.22720699 -0.45229999 -0.22720699 -0.000229   -0.00953191 -0.000229  ]
 [-0.22720699 -0.22720699 -0.45229999 -0.000229   -0.000229   -0.00953191]]


In [8]:
sum(L_ss)

array([-0.90671398, -0.90671398, -0.90671398, -0.00998992, -0.00998992,
       -0.00998992])

In [9]:
sum(L_ss.T)

array([-0.9167039, -0.9167039, -0.9167039])

# 2. Completely uniform

In [10]:
A_2_n = np.array([
    [0.25, 0.25, 0.25],
    [0.25, 0.25, 0.25],
    [0.25, 0.25, 0.25]
])
A_2_c = np.diag([0.25, 0.25, 0.25])

In [11]:
K_ss, L_ss = infinite_solution(A_2_n, A_2_c, delta, c)

In [12]:
print(K_ss)

[[1.01712    0.01712    0.01712    0.00610427 0.00610427 0.00610427]
 [0.01712    1.01712    0.01712    0.00610427 0.00610427 0.00610427]
 [0.01712    0.01712    1.01712    0.00610427 0.00610427 0.00610427]
 [0.00610427 0.00610427 0.00610427 5.85783794 0.17653676 0.17653676]
 [0.00610427 0.00610427 0.00610427 0.17653676 5.85783794 0.17653676]
 [0.00610427 0.00610427 0.00610427 0.17653676 0.17653676 5.85783794]]


In [13]:
sum(K_ss)

array([1.06967281, 1.06967281, 1.06967281, 6.22922426, 6.22922426,
       6.22922426])

In [14]:
print(L_ss)

[[-0.2282667  -0.2282667  -0.2282667  -0.23289159 -0.00563955 -0.00563955]
 [-0.2282667  -0.2282667  -0.2282667  -0.00563955 -0.23289159 -0.00563955]
 [-0.2282667  -0.2282667  -0.2282667  -0.00563955 -0.00563955 -0.23289159]]


In [15]:
sum(L_ss)

array([-0.68480011, -0.68480011, -0.68480011, -0.24417069, -0.24417069,
       -0.24417069])

In [16]:
sum(L_ss.T)

array([-0.92897079, -0.92897079, -0.92897079])

# 3. No inter-agent links

In [17]:
A_3_n = 0.5 * np.identity(3)
A_3_c = np.diag([0.5, 0.5, 0.5])

In [18]:
K_ss, L_ss = infinite_solution(A_3_n, A_3_c, delta, c)

In [19]:
print(np.round(K_ss, 5))

[[ 1.02277  0.       0.       0.02383  0.       0.     ]
 [ 0.       1.02277  0.       0.       0.02383  0.     ]
 [ 0.       0.       1.02277  0.       0.       0.02383]
 [ 0.02383  0.       0.      24.38847  0.       0.     ]
 [ 0.       0.02383  0.       0.      24.38847  0.     ]
 [ 0.       0.       0.02383  0.       0.      24.38847]]


In [20]:
sum(K_ss)

array([ 1.04660391,  1.04660391,  1.04660391, 24.41230315, 24.41230315,
       24.41230315])

In [21]:
print(L_ss)

[[-0.45542673  0.          0.         -0.4766514   0.          0.        ]
 [ 0.         -0.45542673  0.          0.         -0.4766514   0.        ]
 [ 0.          0.         -0.45542673  0.          0.         -0.4766514 ]]


In [22]:
sum(L_ss)

array([-0.45542673, -0.45542673, -0.45542673, -0.4766514 , -0.4766514 ,
       -0.4766514 ])

In [23]:
sum(L_ss.T)

array([-0.93207813, -0.93207813, -0.93207813])