# Unified Model with Integrated Bot: Lower $\delta$, same $c$

James Yu, 17 August 2022

In [1]:
import matplotlib.pyplot as plt
import numpy as np
from numpy.linalg import inv
np.set_printoptions(suppress=True) # disable scientific notation for readability

In [2]:
def infinite_solution(A_n, A_c, delta, c):
    n = 3
    eps = np.finfo(np.float64).eps
    I = np.identity(n)
    O = np.zeros((n, n))
    
    Q = np.block([
        [I, O], 
        [O, O]
    ])
    A = np.block([
        [A_n, A_c], 
        [O, I]
    ])
    B = np.block([
        [I],
        [O]
    ])
    K_t = Q
    K_sequence = [K_t]
    
    while True: # generate solution matrices; note I divide delta into the inverse term for simplification
        K_t_new = Q + delta * A.T @ (K_t - K_t @ B @ inv(B.T @ K_t @ B + c * I / delta) @ B.T @ K_t) @ A
        K_sequence.insert(0, K_t_new)
        if np.allclose(K_t, K_t_new, rtol = eps, atol = eps): break
        K_t = K_t_new

    K_ss = K_sequence[0]
    L_ss = -inv(B.T @ K_ss @ B + c * I / delta) @ B.T @ K_ss @ A
    return K_ss, L_ss

# 1. Highly symmetric

In [3]:
A_1_n = 0.99 * np.array([
    [0.5, 0.25, 0.25],
    [0.25, 0.5, 0.25],
    [0.25, 0.25, 0.5]
])
A_1_c = np.diag([0.01, 0.01, 0.01])
delta = 0.5 # different delta, same c
c = 1.0

In [4]:
K_ss, L_ss = infinite_solution(A_1_n, A_1_c, delta, c)

In [5]:
print(K_ss)

[[1.14856524 0.12786666 0.12786666 0.00252677 0.00161583 0.00161583]
 [0.12786666 1.14856524 0.12786666 0.00161583 0.00252677 0.00161583]
 [0.12786666 0.12786666 1.14856524 0.00161583 0.00161583 0.00252677]
 [0.00252677 0.00161583 0.00161583 0.00009972 0.00002035 0.00002035]
 [0.00161583 0.00252677 0.00161583 0.00002035 0.00009972 0.00002035]
 [0.00161583 0.00161583 0.00252677 0.00002035 0.00002035 0.00009972]]


In [6]:
sum(K_ss)

array([1.41005699, 1.41005699, 1.41005699, 0.00589885, 0.00589885,
       0.00589885])

In [7]:
print(L_ss)

[[-0.19188121 -0.10825059 -0.10825059 -0.00439259 -0.000712   -0.000712  ]
 [-0.10825059 -0.19188121 -0.10825059 -0.000712   -0.00439259 -0.000712  ]
 [-0.10825059 -0.10825059 -0.19188121 -0.000712   -0.000712   -0.00439259]]


In [8]:
sum(L_ss)

array([-0.40838239, -0.40838239, -0.40838239, -0.00581659, -0.00581659,
       -0.00581659])

In [9]:
sum(L_ss.T)

array([-0.41419898, -0.41419898, -0.41419898])

# 2. Completely uniform

In [10]:
A_2_n = np.array([
    [0.25, 0.25, 0.25],
    [0.25, 0.25, 0.25],
    [0.25, 0.25, 0.25]
])
A_2_c = np.diag([0.25, 0.25, 0.25])

In [11]:
K_ss, L_ss = infinite_solution(A_2_n, A_2_c, delta, c)

In [12]:
print(K_ss)

[[1.07076055 0.07076055 0.07076055 0.0307713  0.0307713  0.0307713 ]
 [0.07076055 1.07076055 0.07076055 0.0307713  0.0307713  0.0307713 ]
 [0.07076055 0.07076055 1.07076055 0.0307713  0.0307713  0.0307713 ]
 [0.0307713  0.0307713  0.0307713  0.05219731 0.01053064 0.01053064]
 [0.0307713  0.0307713  0.0307713  0.01053064 0.05219731 0.01053064]
 [0.0307713  0.0307713  0.0307713  0.01053064 0.01053064 0.05219731]]


In [13]:
sum(K_ss)

array([1.30459554, 1.30459554, 1.30459554, 0.16557249, 0.16557249,
       0.16557249])

In [14]:
print(L_ss)

[[-0.0943474  -0.0943474  -0.0943474  -0.09658395 -0.01325062 -0.01325062]
 [-0.0943474  -0.0943474  -0.0943474  -0.01325062 -0.09658395 -0.01325062]
 [-0.0943474  -0.0943474  -0.0943474  -0.01325062 -0.01325062 -0.09658395]]


In [15]:
sum(L_ss)

array([-0.28304219, -0.28304219, -0.28304219, -0.12308519, -0.12308519,
       -0.12308519])

In [16]:
sum(L_ss.T)

array([-0.40612738, -0.40612738, -0.40612738])

# 3. No inter-agent links

In [17]:
A_3_n = 0.5 * np.identity(3)
A_3_c = np.diag([0.5, 0.5, 0.5])

In [18]:
K_ss, L_ss = infinite_solution(A_3_n, A_3_c, delta, c)

In [19]:
print(np.round(K_ss, 5))

[[1.08809 0.      0.      0.10511 0.      0.     ]
 [0.      1.08809 0.      0.      0.10511 0.     ]
 [0.      0.      1.08809 0.      0.      0.10511]
 [0.10511 0.      0.      0.24067 0.      0.     ]
 [0.      0.10511 0.      0.      0.24067 0.     ]
 [0.      0.      0.10511 0.      0.      0.24067]]


In [20]:
sum(K_ss)

array([1.19319285, 1.19319285, 1.19319285, 0.34577449, 0.34577449,
       0.34577449])

In [21]:
print(L_ss)

[[-0.17617498  0.          0.         -0.21021072  0.          0.        ]
 [ 0.         -0.17617498  0.          0.         -0.21021072  0.        ]
 [ 0.          0.         -0.17617498  0.          0.         -0.21021072]]


In [22]:
sum(L_ss)

array([-0.17617498, -0.17617498, -0.17617498, -0.21021072, -0.21021072,
       -0.21021072])

In [23]:
sum(L_ss.T)

array([-0.3863857, -0.3863857, -0.3863857])