# Unified Model with Integrated Bot: Special Examples

James Yu, 14 August 2022

In [1]:
import matplotlib.pyplot as plt
import numpy as np
from numpy.linalg import inv
np.set_printoptions(suppress=True) # disable scientific notation for readability

In [2]:
def infinite_solution(A_n, A_c, delta, c):
    n = 3
    eps = np.finfo(np.float64).eps
    I = np.identity(n)
    O = np.zeros((n, n))
    
    Q = np.block([
        [I, O], 
        [O, O]
    ])
    A = np.block([
        [A_n, A_c], 
        [O, I]
    ])
    B = np.block([
        [I],
        [O]
    ])
    K_t = Q
    K_sequence = [K_t]
    
    while True: # generate solution matrices; note I divide delta into the inverse term for simplification
        K_t_new = Q + delta * A.T @ (K_t - K_t @ B @ inv(B.T @ K_t @ B + c * I / delta) @ B.T @ K_t) @ A
        K_sequence.insert(0, K_t_new)
        if np.allclose(K_t, K_t_new, rtol = eps, atol = eps): break
        K_t = K_t_new

    K_ss = K_sequence[0]
    L_ss = -inv(B.T @ K_ss @ B + c * I / delta) @ B.T @ K_ss @ A
    return K_ss, L_ss

# 1. Highly symmetric

In [3]:
A_1_n = 0.99 * np.array([
    [0.5, 0.25, 0.25],
    [0.25, 0.5, 0.25],
    [0.25, 0.25, 0.5]
])
A_1_c = np.diag([0.01, 0.01, 0.01])
delta = 0.999
c = 1.0

In [4]:
K_ss, L_ss = infinite_solution(A_1_n, A_1_c, delta, c)

In [5]:
print(K_ss)

[[1.22185386 0.19077235 0.19077235 0.00423084 0.00280085 0.00280085]
 [0.19077235 1.22185386 0.19077235 0.00280085 0.00423084 0.00280085]
 [0.19077235 0.19077235 1.22185386 0.00280085 0.00280085 0.00423084]
 [0.00423084 0.00280085 0.00280085 0.0758686  0.01205966 0.01205966]
 [0.00280085 0.00423084 0.00280085 0.01205966 0.0758686  0.01205966]
 [0.00280085 0.00280085 0.00423084 0.01205966 0.01205966 0.0758686 ]]


In [6]:
sum(K_ss)

array([1.61323109, 1.61323109, 1.61323109, 0.10982046, 0.10982046,
       0.10982046])

In [7]:
print(L_ss)

[[-0.28688573 -0.16130388 -0.16130388 -0.00716243 -0.00138471 -0.00138471]
 [-0.16130388 -0.28688573 -0.16130388 -0.00138471 -0.00716243 -0.00138471]
 [-0.16130388 -0.16130388 -0.28688573 -0.00138471 -0.00138471 -0.00716243]]


In [8]:
sum(L_ss)

array([-0.60949349, -0.60949349, -0.60949349, -0.00993186, -0.00993186,
       -0.00993186])

In [9]:
sum(L_ss.T)

array([-0.61942534, -0.61942534, -0.61942534])

# 2. Completely uniform

In [10]:
A_2_n = np.array([
    [0.25, 0.25, 0.25],
    [0.25, 0.25, 0.25],
    [0.25, 0.25, 0.25]
])
A_2_c = np.diag([0.25, 0.25, 0.25])

In [11]:
K_ss, L_ss = infinite_solution(A_2_n, A_2_c, delta, c)

In [12]:
print(K_ss)

[[ 1.10663133  0.10663133  0.10663133  0.05251361  0.05251361  0.05251361]
 [ 0.10663133  1.10663133  0.10663133  0.05251361  0.05251361  0.05251361]
 [ 0.10663133  0.10663133  1.10663133  0.05251361  0.05251361  0.05251361]
 [ 0.05251361  0.05251361  0.05251361 40.42303678  9.18866959  9.18866959]
 [ 0.05251361  0.05251361  0.05251361  9.18866959 40.42303678  9.18866959]
 [ 0.05251361  0.05251361  0.05251361  9.18866959  9.18866959 40.42303678]]


In [13]:
sum(K_ss)

array([ 1.47743484,  1.47743484,  1.47743484, 58.95791681, 58.95791681,
       58.95791681])

In [14]:
print(L_ss)

[[-0.14217511 -0.14217511 -0.14217511 -0.1533098  -0.02837233 -0.02837233]
 [-0.14217511 -0.14217511 -0.14217511 -0.02837233 -0.1533098  -0.02837233]
 [-0.14217511 -0.14217511 -0.14217511 -0.02837233 -0.02837233 -0.1533098 ]]


In [15]:
sum(L_ss)

array([-0.42652533, -0.42652533, -0.42652533, -0.21005446, -0.21005446,
       -0.21005446])

In [16]:
sum(L_ss.T)

array([-0.63657979, -0.63657979, -0.63657979])

# 3. No inter-agent links

In [17]:
A_3_n = 0.5 * np.identity(3)
A_3_c = np.diag([0.5, 0.5, 0.5])

In [18]:
K_ss, L_ss = infinite_solution(A_3_n, A_3_c, delta, c)

In [19]:
print(np.round(K_ss, 5))

[[  1.13272   0.        0.        0.17333   0.        0.     ]
 [  0.        1.13272   0.        0.        0.17333   0.     ]
 [  0.        0.        1.13272   0.        0.        0.17333]
 [  0.17333   0.        0.      199.88523   0.        0.     ]
 [  0.        0.17333   0.        0.      199.88523   0.     ]
 [  0.        0.        0.17333   0.        0.      199.88523]]


In [20]:
sum(K_ss)

array([  1.3060505 ,   1.3060505 ,   1.3060505 , 200.05856383,
       200.05856383, 200.05856383])

In [21]:
print(L_ss)

[[-0.26543261  0.          0.         -0.34666839  0.          0.        ]
 [ 0.         -0.26543261  0.          0.         -0.34666839  0.        ]
 [ 0.          0.         -0.26543261  0.          0.         -0.34666839]]


In [22]:
sum(L_ss)

array([-0.26543261, -0.26543261, -0.26543261, -0.34666839, -0.34666839,
       -0.34666839])

In [23]:
sum(L_ss.T)

array([-0.612101, -0.612101, -0.612101])